// Package indexbench provides the shared corpus and edit scenarios used to
// benchmark code indexers (the current graph and the chronos indexer) against
// identical inputs. It is only imported from tests and benchmarks.
package indexbench

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// CopyRepo copies every tracked and untracked, non-ignored file of the git
// checkout at src into a fresh temporary directory and returns its path.
// Relative go.mod replace directives are rewritten to absolute paths so the
// copy still type-checks. The copy is removed when tb finishes.
func CopyRepo(tb testing.TB, src string) string {
	tb.Helper()
	out, err := exec.Command("git", "-C", src, "ls-files", "-z", "--cached", "--others", "--exclude-standard").Output()
	if err != nil {
		tb.Fatalf("list files in %s: %v", src, err)
	}
	dst := tb.TempDir()
	if canonical, err := filepath.EvalSymlinks(dst); err == nil {
		dst = canonical
	}
	for _, rel := range strings.Split(strings.TrimRight(string(out), "\x00"), "\x00") {
		if rel == "" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(src, rel))
		if os.IsNotExist(err) {
			continue // deleted in the worktree but still in the index
		}
		if err != nil {
			tb.Fatalf("read %s: %v", rel, err)
		}
		if rel == "go.mod" {
			data = absReplaces(data, src)
		}
		target := filepath.Join(dst, rel)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			tb.Fatalf("mkdir for %s: %v", rel, err)
		}
		if err := os.WriteFile(target, data, 0o644); err != nil {
			tb.Fatalf("write %s: %v", rel, err)
		}
	}
	return dst
}

// absReplaces rewrites `=> ./x` and `=> ../x` replace targets relative to src.
func absReplaces(mod []byte, src string) []byte {
	lines := bytes.Split(mod, []byte("\n"))
	for i, line := range lines {
		lhs, rhs, ok := bytes.Cut(line, []byte("=>"))
		if !ok {
			continue
		}
		target := strings.TrimSpace(string(rhs))
		if !strings.HasPrefix(target, "./") && !strings.HasPrefix(target, "../") {
			continue
		}
		lines[i] = []byte(fmt.Sprintf("%s=> %s", lhs, filepath.Join(src, target)))
	}
	return bytes.Join(lines, []byte("\n"))
}

// Probe owns one generated file inside an existing package of a corpus and
// rewrites it to produce the edit shapes an indexer must handle. Every write
// moves the file's mtime forward so metadata-based change detection never
// misses an edit.
type Probe struct {
	tb    testing.TB
	path  string
	pkg   string
	mtime time.Time
}

// NewProbe creates the probe file in dir (relative to root), declaring package
// pkg, in its baseline state.
func NewProbe(tb testing.TB, root, dir, pkg string) *Probe {
	tb.Helper()
	p := &Probe{tb: tb, path: filepath.Join(root, dir, "zz_indexbench_probe.go"), pkg: pkg, mtime: time.Now()}
	p.Write(0, false, true)
	return p
}

// Path returns the probe file's absolute path.
func (p *Probe) Path() string { return p.path }

// Write renders the probe. body changes only a function body; wideSig changes
// the exported function's signature; extra controls whether a second exported
// declaration exists (toggling it adds or removes a declaration).
func (p *Probe) Write(body int, wideSig, extra bool) {
	p.tb.Helper()
	var b strings.Builder
	fmt.Fprintf(&b, "package %s\n\n", p.pkg)
	if wideSig {
		fmt.Fprintf(&b, "// IndexBenchProbe is generated by indexbench.\nfunc IndexBenchProbe(n int) int { return n + %d }\n", body)
	} else {
		fmt.Fprintf(&b, "// IndexBenchProbe is generated by indexbench.\nfunc IndexBenchProbe() int { return %d }\n", body)
	}
	if extra {
		b.WriteString("\n// IndexBenchProbeExtra is generated by indexbench.\nfunc IndexBenchProbeExtra() int { return IndexBenchProbeHelper() }\n")
		b.WriteString("\nfunc IndexBenchProbeHelper() int { return 1 }\n")
	}
	if err := os.WriteFile(p.path, []byte(b.String()), 0o644); err != nil {
		p.tb.Fatalf("write probe: %v", err)
	}
	p.mtime = p.mtime.Add(time.Second)
	if err := os.Chtimes(p.path, p.mtime, p.mtime); err != nil {
		p.tb.Fatalf("touch probe: %v", err)
	}
}
